Add batch calls
PureStake/crowdloan-rewards pull request #1
Opened 2021-03-25 09:42 UTC by girazoki

2021-03-25 12:19 UTC, JoshOrndorff commented
Did you change something about the white space here? It looks like nearly the entire pallet changed in the diff. Makes it hard to find what you actually changed.

2021-03-25 13:44 UTC, girazoki commented
I shouldnt have done it on purpose, but let me check what I can do. Otherwise I will open another PR

2021-03-25 13:46 UTC, girazoki commented
I see, its cargo fmt that did all this changes. I can push a commit in between updating only the fmt stuff if you prefer

2021-03-25 13:53 UTC, girazoki commented
Done, now the second commit points to the real batch call changes

2021-03-29 16:24 UTC, JoshOrndorff requested changes
We shouldn't need to copy the code from the utility pallet into our pallet. Rather, just install the utility pallet in the runtime (in this repo there is just the mock runtime). Then in your tests call into the utility pallet's copy of the code.

Concretely, we already have the utility pallet in the moonbeam runtime.

2021-03-31 13:37 UTC, girazoki commented on src/mock.rs
> +		Utility::on_initialize(System::block_number());
actually for my tests it seems I just need set_block_number, so I will remove the rest

2021-03-31 13:42 UTC, girazoki commented
Cool!

There are two more changes that I am planning to add:
- If you call initialize_vec_reward with a vector of contributions, and one contribution is wrong, skip it without reverting and continue with the following one. I will still emit an event for us to know that one of them was wrong.
- Add pallet-utility and pallet-balances as depenencies instead of dev-dependencies. The reason being that if I import this pallet from moonbeam it complaints about missing std features in both pallets. I have checked pallet-staking and also has pallet-balances as dependency even if it is only used in the tests, I suspect that for the same reason.

2021-04-02 08:33 UTC, merged